- src/use-case/floor-plan-converted-to-editable-3d-model.md
Added some text about what happens, input files we accept, a sample floor plan which corresponds to the output we show. Pls review scaling of the image - couldn't do w mark-down, used html.
> Expand 2D->3D page

- src/partner-application.md
for certified partners: content creators and web authors
> Adding transparent pricing as a requirement

- package-lock.json
- src/docs/api/1/aframe-components.md
- src/docs/api/1/furniture-library.md
- src/products.json
> Adds furniture app to docs and products

- src/floor-plan-to-3d-conversion.pug
keeping consistency across spaces and 3d.io (decided on premium with the sales team)
@tomas-polach please change the image 'img/2d-to-3d-with-partner.jpg'
to reflect the change from "professional" to "premium" models
> Change professional to premium model

- src/index.pug
**steps:**
- go to 3d.io
- in the first text
- click on "3D import"
**actual result**: 404 error
**expected result**:
arrive at https://3d.io/use-case/virtually-staged-3d-scan.html
> Error in Link for 3D Import

- src/pug-common/footer.pug
Goal: learn what people do on 3d.io landing page. 
Tool used: hotjar heatmap and recordings tool.
- under the 15 days free trial
- website:https://www.hotjar.com/
Implementation: added tracking code to footer of the page
(adapted tracking code to pugjs from html)
<script>
(function(h,o,t,j,a,r){
h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
h._hjSettings={hjid:636151,hjsv:5};
a=o.getElementsByTagName('head')[0];
r=o.createElement('script');r.async=1;
r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
a.appendChild(r);
})(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');
</script>
> Adding Hotjar heatmap tracking

- src/partners.pug
changing label name of google analytics event for consistency
> Changing Google Analytics event label for consistency on the partners overview

- src/pug-common/partner-profile-page.pug
changing label from url and email to name so that we can group the action by name
> Changing Google Analytics Event Label name for consistency on individual partner page

- src/docs/api/1/aframe-components.md
- src/docs/api/1/home-staging-ai.md
- src/docs/api/1/index.md
- src/docs/api/1/scene.md
- src/products.json
* Added docs on scene API
/docs/api/1/scene.html
* Added missing references
> Scene structure

- src/docs/api/1/convert-floor-plan-to-3d.md
- src/docs/api/1/home-staging-ai.md
- src/docs/api/1/index.md
- src/products.json
* added missing floor plan conversion API documentation
* preview:
https://3d.io/branch/floorPlanConversion/docs/api/1/convert-floor-plan-to-3d.html
> Floor plan conversion

- src/docs/api/1/home-staging-ai.md
I don't really understand this phrase: line 70
"this will take the first space it finds
and furnish it with Living and Dining
output is the sceneStructure of the furnishing"
> Corrected typos in doc home staging ai

- src/docs/api/1/home-staging-ai.md
- Improved home staging docs for clarity
- Tested out and fixed code examples
- Added live demos of the code examples in App Creator
> Improve home staging docs

- src/pug-common/footer.pug
For Cross domain tracking need to set a linker.
see
https://github.com/archilogic-com/services/issues/352
> Add "Linker" in the Google Analytics Code

- src/partners.pug
Changed the order of where each partner is displayed on the page to see if it effects the click rate.
> Change order of Partners on Partner Page

- src/partner/3d-vision.md
Adding an additional certified partner to our partner page on 3d.io
> Add 3D Vision as a Certified Partner

- src/docs/api/1/index.md
- src/docs/api/1/lightmap-baking.md
- src/docs/api/1/model-export.md
- src/docs/api/1/modify.md
- src/products.json
Scope & Features:
- Documents changes from this [PR](https://github.com/archilogic-com/3dio-js/pull/90)
- Updated API documentation draft for [modify](https://3d.io/branch/processing-api-documentation/docs/api/1/modify.html), [light baking](https://3d.io/branch/processing-api-documentation/docs/api/1/lightmap-baking.html), [model export](https://3d.io/branch/processing-api-documentation/docs/api/1/model-export.html)
Notes: 
- should be merged AFTER above PR has been released.
> Processing api documentation

- src/docs/api/1/modify.md
> Added documentation for modify collision object

- package-lock.json
- src/index.pug
Per our discussion yesterday. Backend still needs to get adjusted to new limits.
> Changed Pricing Tables

- src/docs/api/1/modify.md
Please test @bnjm and merge pull request after next release.
> Added documentation:  ratio to modify.origami options

- src/docs/api/1/aframe-components.md
availableMaterials is one level up
> updated components
